# Generated by Django 6.0 on 2026-03-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_created_at_profile_cv_profile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
