# Generated by Django 6.0 on 2026-01-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=60)),
                ('price', models.PositiveIntegerField(help_text='Price per hour in AED')),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=2)),
                ('bio', models.TextField(blank=True)),
                ('lessons', models.PositiveIntegerField(default=0)),
                ('students', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
