# Generated by Django 6.0 on 2026-02-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tutor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tutors/photos/'),
        ),
    ]
